module.exports = {

	PARTY_INVITE_SEND: 0,
	PARTY_INVITE_RECEIVE: 1,
	PARTY_INVITE_ACCEPT: 2,
	PARTY_INVITE_DECLINE: 3,

	MATCHMAKING_START: 4,
	MATCHMAKING_CANCEL: 5,
	MATCHMAKING_MATCH_FOUND: 6,
	MATCHMAKING_MATCH_CANCELLED: 7,
	MATCHMAKING_MATCH_JOIN: 8,
	MATCHMAKING_MATCH_COMPLETE: 9,

	ERROR: 10,
	CONNECT_SUCCESS: 11,
	CONNECT: 12,
	IDENTIFY: 13,
	REFRESH: 14,


};